/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Blip {
  id: Generated<number>;
  radar_version_id: number;
  ring: number;
  tech_id: number;
}

export interface Quadrant {
  id: number;
  name: string;
}

export interface Radar {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  name: string;
  public_id: string;
}

export interface RadarVersion {
  id: Generated<number>;
  radar_id: number;
  version: number;
  label: string | null;
  release_date: ColumnType<Date, Date | string, Date | string>;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface Ring {
  color: string;
  id: number;
  name: string;
}

export interface Tech {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<number>;
  name: string;
  public_id: string;
  quadrant: number;
  updated_at: Generated<Timestamp | null>;
  url: string | null;
}

export interface DB {
  blip: Blip;
  quadrant: Quadrant;
  radar: Radar;
  radar_version: RadarVersion;
  ring: Ring;
  tech: Tech;
}
